### ISSUE TITLE
Impossible to reply to newcomer group member

### ISSUE THREAD

**Issue by MK1973** [ubports/telegram-app#123] opened 2017-12-05 16:06 UTC
Can not reply clicking on new coming member link in super group. 
Not tested if there is the same issue behavior on standard group.
version: 2.5.1.0, OS channel, devel, Nexus 5

**Comment by PeterNerlich** [comment] 2017-12-21 11:54
possible duplicate of/related to #120?

**Comment by Flohack74** [comment] 2017-12-21 13:14
No nothing to do with that. Newcomer messages are "MessageAction" objects, while normal messages are of type "Message". There is no swipe function defined for MessageAction objects, and that needs some thorough design to extend the functionality. Simply was not planned by the original upstream to support this. The #120 is about external links from Oxide web browser.

**Comment by Flohack74** [comment] 2018-08-21 19:42
I found an easy solution for this. Will be in next update...

**Closed** 2018-12-11 14:04 UTC
