### ISSUE TITLE
Captions (below photos) are not displayed

### ISSUE THREAD

**Issue by GI9VANNI** [ubports/telegram-app#183] opened 2018-06-20 18:57 UTC
When I receive a photo with a caption, the caption is not displayed on Ubuntu Touch.
While on Android is displayed well, on Ubuntu you see only the photo without the caption.
Nevertheless, the caption appears in the Ubuntu Touch notification bar.

**Comment by Flohack74** [comment] 2018-06-20 20:08
Duplicate of #58

**Closed by Flohack74** 2018-06-20 20:08 UTC
