### ISSUE TITLE
Telegram does not read the contacts sent by android devices via telegram

### ISSUE THREAD

**Issue by Gabriele69** [ubports/telegram-app#119] opened 2017-11-20 15:33 UTC
Hello to all.
I've seen that when someone sends me a contact from your device android, this is not properly displayed (not even imported) from our Telegram.
I have a BQ 4.5 RC 9 with Telegram vers. 04/02/42

**Comment by Flohack74** [comment] 2017-11-20 18:14
Duplicate of #23

**Closed by Flohack74** 2017-11-20 18:14 UTC
Labels: duplicate
