### ISSUE TITLE
[xenial] Clipboard paste is broken in send message text input field

### ISSUE THREAD

**Issue by zubozrout** [ubports/telegram-app#176] opened 2018-05-25 16:41 UTC
Hello,
I am completely unable to paste content from clipboard to the Telegram text input field.

This issue is persistent from Vivid although there it only broke sometimes and restarting Telegram usually fixed the issue. On Xenial nothing I do seems to help.

**Steps to reproduce:**
1. Copy something to clipboard, even text present in Telegram text input field.
2. Try to paste the content of the clipboard to the Telegram text input field.

**Expected behaviour:**
Text content gets pasted in.

**Current behaviour:**
The popup paste icon disappears but no text is pasted.

Thank you very much for looking into this.

My Telegram version: 2.5.3.2
My Ubuntu version: Ubuntu 16.04 r85
My device: Meizu MX4 (arale)

**Comment by advocatux** [comment] 2018-05-25 17:22
I can confirm this bug in BQ E4.5 (Krillin) running Ubuntu 16.04 (r85).

**Comment by zubozrout** [comment] 2018-05-31 07:56
So, even if I clean the text input from most of the additional functions or change the TextArea with TextField I am using in my own application paste still doesn't work for me :(.
Copying or cutting text from the filed works just fine but pasting doesn't do anything and it doesn't even change any of the event handlers listed on the TextArea here AccountMessageList.qml
I've also tried TextInput but these pop-up tools doesn't work there at all.

It also doesn't look like it has anything to do with other things connected to the original text input field as I've also tried hiding that one and showing another text input with different id instead of it.

**Comment by zubozrout** [comment] 2018-05-31 07:58
Ok, so I've just checked and all input fields in Telegram won't allow to paste stuff from clipboard (contact search field, account settings: name)

**Comment by zubozrout** [comment] 2018-06-06 18:53
Ok, so on r89 Xenial (Meizu MX4 arale) clipboard paste doesn't work at all in any of the apps :(. I can copy/cut from text fields but pasting using long-press is broken everywhere. I can however paste in "tedit" app from the OpenStore using its in-app menu and "Paste from clipboard" option or in Terminal.

**Comment by advocatux** [comment] 2018-06-06 19:36
I can confirm it.
Copy&paste doesn't work in any of the apps I've been testing on a BQ E4.5 (Krillin) running Ubuntu 16.04 (r89).

**Comment by Flohack74** [comment] 2018-06-07 12:20
Can it be that it never worked?

**Comment by advocatux** [comment] 2018-06-07 12:48
_Maybe... ?_

I really don't remember how it worked before or if it worked at all.

**Comment by zubozrout** [comment] 2018-06-07 16:28
It certainly worked on Vivid ... I recall using it to paste stuff from my app and send it like that. And I did that pretty often though sometimes hat to restart Telegram to get it working again. And my brother used to paste links from web browser the same way and also experienced exactly the same behaviour when restarting Telegram restored the paste functionality for him too.

However the last time I was on Vivid was maybe back in September last year.

**Comment by mauricioduarte01** [comment] 2018-06-10 23:05
Afaik that feature never worked....

**Comment by Flohack74** [comment] 2018-06-11 16:31
This seems to be a problem of all Apps in xenial, not only Telegram: https://github.com/ubports/ubuntu-touch/issues/658 - So closing this here.

**Closed by Flohack74** 2018-06-11 16:31 UTC
Labels: bug

**Comment by zubozrout** [comment] 2018-06-11 19:22
@Flohack74 - Yeah, I've reported that as well :). But as you can see that issue is most probably unrelated because it was introduced in later builds and Telegram didn't work before it broke system-wide either. So I don't think this should be closed yet.

**Comment by zubozrout** [comment] 2018-06-18 07:48
@Flohack74 Ok, so you were apparently right, sorry. With the latest Xenial release (90 on Arale) clipboard paste seems to work now :).
